apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd-namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.5/manifests/install.yaml
- argocd-project.yaml
- argocd-dev-services.applicationset.yaml
patchesStrategicMerge:
- argocd-overrides.yaml
