apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azurekv-secret-store
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "d3bc2180-xxxx-xxxx-xxxx-154105743342"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://my-keyvault-name.vault.azure.net"
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          namespace: external-secrets
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          namespace: external-secrets
          name: azure-secret-sp
          key: ClientSecret
