apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-main
  labels: 
    app.kubernetes.io/name: grafana-main
    dashboards: "grafana"
spec:
  deployment:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-main
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: grafana-main
        spec:
          containers:
          - name: grafana
            image: grafana/grafana-oss:latest
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
  service:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-main
    spec:
      type: ClusterIP
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: "true"
    auth:
      disable_login_form: "false"
      disable_signout_menu: "true"
    auth.anonymous:
      enabled: "true"
      org_role: "Editor"