apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-main
  labels: 
    app.kubernetes.io/name: grafana-main
    dashboards: "grafana"
spec:
  deployment:
    labels:
      app.kubernetes.io/name: grafana-main
  client:
    preferService: true
  service:
    name: grafana-main
    labels:
      app.kubernetes.io/name: grafana-main
    type: ClusterIP
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
      org_role: Editor
  resources:
    # Optionally specify container resources
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi