# Set defaul Grafana version to "lastest".
# Scan for dashboards in all namespaces.
apiVersion: apps/v1
kind: Deployment
metadata:
   name: controller-manager
   namespace: system
   labels:
    control-plane: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --health-probe-bind-address=:8081             # existing arg from deployment
            - --metrics-bind-address=127.0.0.1:8080         # existing arg from deployment
            - --zap-log-level=error                         # existing arg from deployment
            - --grafana-image-tag=latest                    # set default Grafana version to "latest"
