apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
- github.com/grafana-operator/grafana-operator/deploy/kustomize/overlays/cluster_scoped
- grafana-main.grafana.yaml
- grafana-main-mapping.yaml
- victoria-metrics.grafanadatasource.yaml
- victoria-metrics.grafanadashboard.yaml 
- vm-agent.grafanadashboard.yaml 
- kubernetes.grafanadashboard.yaml
- kubernetes2.grafanadashboard.yaml

patches:
- path: grafana-operator-overrides.yaml