apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

helmChartInflationGenerator:
- chartName: external-secrets
  chartRepoUrl: https://charts.external-secrets.io
  #chartVersion: v0.5.2   # will use "latest" when not specified
  releaseNamespace: external-secrets
  releaseName: external-secrets
  values: values.yaml
  extraArgs:
  - --skip-crds

resources:
- external-secrets-namespace.yaml 
- https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml