apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
resources:
- argo-events-namespace.yaml  
- https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml 
- https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml 
- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml 