# Don't use kube-system for leader election--use own namespace instead.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
        - name: cert-manager
          args:
            - --v=2                                         # existing arg from deployment
            - --cluster-resource-namespace=$(POD_NAMESPACE) # existing arg from deployment
            - --leader-election-namespace=cert-manager      # use own namespace for leader election
