apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-ui
  namespace: argocd
spec:
  hostname: argocd.localhost
  prefix: /
  service: argocd-server:443
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-cli
  namespace: argocd
spec:
  hostname: argocd.localhost:443
  prefix: /
  service: argocd-server:443