apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- argo-namespace.yaml
- argo-mapping.yaml 
- https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml 
- minio-storage-class.yaml 
patchesStrategicMerge:
- argo-overrides.yaml