apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoria-metrics

resources:
- github.com/VictoriaMetrics/operator/config/default?ref=v0.34.1
- vmsingle.yaml
- vmagent.yaml
- mappings.yaml
- pushgateway.yaml
- pushgateway.vmservicescrape.yaml
- ca-node-scrape.vmnodescrape.yaml
- node-scrape.vmnodescrape.yaml

#patchesStrategicMerge:
#  - delete-psp-clusterrole.patch.yaml
#  - delete-psp-clusterrolebinding.patch.yaml
#  - delete-psp.patch.yaml 

images:
- name: victoriametrics/operator
  newTag: v0.34.1