apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoria-metrics

resources:
- victoria-metrics.namespace.yaml
- github.com/VictoriaMetrics/operator/config/default?ref=v0.28.5
- vmsingle.yaml
- vmagent.yaml
- mappings.yaml
- pushgateway.yaml
- pushgateway.vmservicescrape.yaml
- ca-node-scrape.vmnodescrape.yaml
- node-scrape.vmnodescrape.yaml

patchesStrategicMerge:
  - delete-psp-clsuterrole.patch.yaml
  - delete-psp-clsuterrolebinding.patch.yaml
  - delete-psp.patch.yaml 

images:
- name: victoriametrics/operator
  newTag: v0.28.5